#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

# Update, Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Load balancer configuration
server_script=\
"
frontend  ueudje_frontend
        bind *:80
        mode http
        default_backend ueudje_backend
backend ueudje_backend
        balance roundrobin
        server 371891-web-01 52.205.146.1:80 check
        server 371891-web-02 54.242.204.250:80 check
"
echo "$server_script" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enabling init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing for syntax errors
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Reloading the Nginx service
sudo service haproxy restart
